export const FETCH_DRONE_DETAILS = "COMMAND/FETCH_DRONE_DETAILS_FOR_METRIC_DATA"
export const FETCH_WEATHER = "COMMAND/FETCH_WEATHER_FOR_LAT_LNG";
export const API_ERROR = "EVENT/API_ERROR_RECEIVED";
export const WEATHER_DATA_RECEIVED = "EVENT/WEATHER_DATA_RECEIVED";
export const WEATHER_ID_RECEIVED = "EVENT/WEATHER_ID_RECEIVED";
export const DRONE_METRICS_DATA_RECEVED = "EVENT/DRONE_METRICS_DATA_RECEVED";
